services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - chat-network
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540
    networks:
      - chat-network
networks:
  chat-network:
    driver: bridge