services:
  tabletap-api:
    image: tabletap-api
    container_name: tabletap-api
    networks:
      - caddy_network
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - caddy

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    networks:
      - caddy_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_network:
    name: caddy_network
    driver: bridge