spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI}
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    email-from: ${SENDGRID_EMAIL_FROM}
---
# Development properties
spring:
  config:
    activate:
      on-profile: dev
  frontend:
    url: ${FRONTEND_URL_DEV}
  backend:
    url: ${BACKEND_URL_DEV}